/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntelGridRouteImport } from './routes/intel-grid'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TapRouteImport } from './routes/tap'
import { Route as ApiFirecrawlInboxRouteImport } from './routes/api/firecrawl/inbox'
import { Route as ApiFirecrawlIntelRouteImport } from './routes/api/firecrawl/intel'
import { Route as ApiFirecrawlPullRouteImport } from './routes/api/firecrawl/pull'
import { Route as ApiFirecrawlRadarRouteImport } from './routes/api/firecrawl/radar'
import { Route as ApiFirecrawlWebhookRouteImport } from './routes/api/firecrawl/webhook'
import { Route as ApiLiveAskRouteImport } from './routes/api/live/ask'
import { Route as ApiLiveBacktestRouteImport } from './routes/api/live/backtest'
import { Route as ApiLiveBriefRouteImport } from './routes/api/live/brief'
import { Route as ApiLiveBrtiRouteImport } from './routes/api/live/brti'
import { Route as ApiLiveDeskRouteImport } from './routes/api/live/desk'
import { Route as ApiLiveGrokRouteImport } from './routes/api/live/grok'
import { Route as ApiLiveHeartRouteImport } from './routes/api/live/heart'
import { Route as ApiLiveKalshiRouteImport } from './routes/api/live/kalshi'
import { Route as ApiLiveKalshiOrderRouteImport } from './routes/api/live/kalshi-order'
import { Route as ApiLiveLeverageRouteImport } from './routes/api/live/leverage'
import { Route as ApiLivePerpFireRouteImport } from './routes/api/live/perp-fire'
import { Route as ApiLivePmusRouteImport } from './routes/api/live/pmus'
import { Route as ApiLivePriceRouteImport } from './routes/api/live/price'
import { Route as ApiLivePythRouteImport } from './routes/api/live/pyth'
import { Route as ApiLiveScanRouteImport } from './routes/api/live/scan'
import { Route as ApiLiveSkillRouteImport } from './routes/api/live/skill'
import { Route as ApiLiveSwarmRouteImport } from './routes/api/live/swarm'
import { Route as ApiLiveTapeRouteImport } from './routes/api/live/tape'
import { Route as ApiLiveTelegramRouteImport } from './routes/api/live/telegram'
import { Route as ApiLiveSwarmFeedRouteImport } from './routes/api/live/swarm/feed'
import { Route as ApiLiveSwarmStreamRouteImport } from './routes/api/live/swarm/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelGridRoute = IntelGridRouteImport.update({
  id: '/intel-grid',
  path: '/intel-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TapRoute = TapRouteImport.update({
  id: '/tap',
  path: '/tap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlInboxRoute = ApiFirecrawlInboxRouteImport.update({
  id: '/api/firecrawl/inbox',
  path: '/api/firecrawl/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlIntelRoute = ApiFirecrawlIntelRouteImport.update({
  id: '/api/firecrawl/intel',
  path: '/api/firecrawl/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlPullRoute = ApiFirecrawlPullRouteImport.update({
  id: '/api/firecrawl/pull',
  path: '/api/firecrawl/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlRadarRoute = ApiFirecrawlRadarRouteImport.update({
  id: '/api/firecrawl/radar',
  path: '/api/firecrawl/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlWebhookRoute = ApiFirecrawlWebhookRouteImport.update({
  id: '/api/firecrawl/webhook',
  path: '/api/firecrawl/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveAskRoute = ApiLiveAskRouteImport.update({
  id: '/api/live/ask',
  path: '/api/live/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveBacktestRoute = ApiLiveBacktestRouteImport.update({
  id: '/api/live/backtest',
  path: '/api/live/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveBriefRoute = ApiLiveBriefRouteImport.update({
  id: '/api/live/brief',
  path: '/api/live/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveBrtiRoute = ApiLiveBrtiRouteImport.update({
  id: '/api/live/brti',
  path: '/api/live/brti',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveDeskRoute = ApiLiveDeskRouteImport.update({
  id: '/api/live/desk',
  path: '/api/live/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveGrokRoute = ApiLiveGrokRouteImport.update({
  id: '/api/live/grok',
  path: '/api/live/grok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveHeartRoute = ApiLiveHeartRouteImport.update({
  id: '/api/live/heart',
  path: '/api/live/heart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveKalshiRoute = ApiLiveKalshiRouteImport.update({
  id: '/api/live/kalshi',
  path: '/api/live/kalshi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveKalshiOrderRoute = ApiLiveKalshiOrderRouteImport.update({
  id: '/api/live/kalshi-order',
  path: '/api/live/kalshi-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveLeverageRoute = ApiLiveLeverageRouteImport.update({
  id: '/api/live/leverage',
  path: '/api/live/leverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivePerpFireRoute = ApiLivePerpFireRouteImport.update({
  id: '/api/live/perp-fire',
  path: '/api/live/perp-fire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivePmusRoute = ApiLivePmusRouteImport.update({
  id: '/api/live/pmus',
  path: '/api/live/pmus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivePriceRoute = ApiLivePriceRouteImport.update({
  id: '/api/live/price',
  path: '/api/live/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivePythRoute = ApiLivePythRouteImport.update({
  id: '/api/live/pyth',
  path: '/api/live/pyth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveScanRoute = ApiLiveScanRouteImport.update({
  id: '/api/live/scan',
  path: '/api/live/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSkillRoute = ApiLiveSkillRouteImport.update({
  id: '/api/live/skill',
  path: '/api/live/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSwarmRoute = ApiLiveSwarmRouteImport.update({
  id: '/api/live/swarm',
  path: '/api/live/swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveTapeRoute = ApiLiveTapeRouteImport.update({
  id: '/api/live/tape',
  path: '/api/live/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveTelegramRoute = ApiLiveTelegramRouteImport.update({
  id: '/api/live/telegram',
  path: '/api/live/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSwarmFeedRoute = ApiLiveSwarmFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => ApiLiveSwarmRoute,
} as any)
const ApiLiveSwarmStreamRoute = ApiLiveSwarmStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiLiveSwarmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intel-grid': typeof IntelGridRoute
  '/paper': typeof PaperRoute
  '/research': typeof ResearchRoute
  '/tap': typeof TapRoute
  '/api/firecrawl/inbox': typeof ApiFirecrawlInboxRoute
  '/api/firecrawl/intel': typeof ApiFirecrawlIntelRoute
  '/api/firecrawl/pull': typeof ApiFirecrawlPullRoute
  '/api/firecrawl/radar': typeof ApiFirecrawlRadarRoute
  '/api/firecrawl/webhook': typeof ApiFirecrawlWebhookRoute
  '/api/live/ask': typeof ApiLiveAskRoute
  '/api/live/backtest': typeof ApiLiveBacktestRoute
  '/api/live/brief': typeof ApiLiveBriefRoute
  '/api/live/brti': typeof ApiLiveBrtiRoute
  '/api/live/desk': typeof ApiLiveDeskRoute
  '/api/live/grok': typeof ApiLiveGrokRoute
  '/api/live/heart': typeof ApiLiveHeartRoute
  '/api/live/kalshi': typeof ApiLiveKalshiRoute
  '/api/live/kalshi-order': typeof ApiLiveKalshiOrderRoute
  '/api/live/leverage': typeof ApiLiveLeverageRoute
  '/api/live/perp-fire': typeof ApiLivePerpFireRoute
  '/api/live/pmus': typeof ApiLivePmusRoute
  '/api/live/price': typeof ApiLivePriceRoute
  '/api/live/pyth': typeof ApiLivePythRoute
  '/api/live/scan': typeof ApiLiveScanRoute
  '/api/live/skill': typeof ApiLiveSkillRoute
  '/api/live/swarm': typeof ApiLiveSwarmRouteWithChildren
  '/api/live/tape': typeof ApiLiveTapeRoute
  '/api/live/telegram': typeof ApiLiveTelegramRoute
  '/api/live/swarm/feed': typeof ApiLiveSwarmFeedRoute
  '/api/live/swarm/stream': typeof ApiLiveSwarmStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intel-grid': typeof IntelGridRoute
  '/paper': typeof PaperRoute
  '/research': typeof ResearchRoute
  '/tap': typeof TapRoute
  '/api/firecrawl/inbox': typeof ApiFirecrawlInboxRoute
  '/api/firecrawl/intel': typeof ApiFirecrawlIntelRoute
  '/api/firecrawl/pull': typeof ApiFirecrawlPullRoute
  '/api/firecrawl/radar': typeof ApiFirecrawlRadarRoute
  '/api/firecrawl/webhook': typeof ApiFirecrawlWebhookRoute
  '/api/live/ask': typeof ApiLiveAskRoute
  '/api/live/backtest': typeof ApiLiveBacktestRoute
  '/api/live/brief': typeof ApiLiveBriefRoute
  '/api/live/brti': typeof ApiLiveBrtiRoute
  '/api/live/desk': typeof ApiLiveDeskRoute
  '/api/live/grok': typeof ApiLiveGrokRoute
  '/api/live/heart': typeof ApiLiveHeartRoute
  '/api/live/kalshi': typeof ApiLiveKalshiRoute
  '/api/live/kalshi-order': typeof ApiLiveKalshiOrderRoute
  '/api/live/leverage': typeof ApiLiveLeverageRoute
  '/api/live/perp-fire': typeof ApiLivePerpFireRoute
  '/api/live/pmus': typeof ApiLivePmusRoute
  '/api/live/price': typeof ApiLivePriceRoute
  '/api/live/pyth': typeof ApiLivePythRoute
  '/api/live/scan': typeof ApiLiveScanRoute
  '/api/live/skill': typeof ApiLiveSkillRoute
  '/api/live/swarm': typeof ApiLiveSwarmRouteWithChildren
  '/api/live/tape': typeof ApiLiveTapeRoute
  '/api/live/telegram': typeof ApiLiveTelegramRoute
  '/api/live/swarm/feed': typeof ApiLiveSwarmFeedRoute
  '/api/live/swarm/stream': typeof ApiLiveSwarmStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intel-grid': typeof IntelGridRoute
  '/paper': typeof PaperRoute
  '/research': typeof ResearchRoute
  '/tap': typeof TapRoute
  '/api/firecrawl/inbox': typeof ApiFirecrawlInboxRoute
  '/api/firecrawl/intel': typeof ApiFirecrawlIntelRoute
  '/api/firecrawl/pull': typeof ApiFirecrawlPullRoute
  '/api/firecrawl/radar': typeof ApiFirecrawlRadarRoute
  '/api/firecrawl/webhook': typeof ApiFirecrawlWebhookRoute
  '/api/live/ask': typeof ApiLiveAskRoute
  '/api/live/backtest': typeof ApiLiveBacktestRoute
  '/api/live/brief': typeof ApiLiveBriefRoute
  '/api/live/brti': typeof ApiLiveBrtiRoute
  '/api/live/desk': typeof ApiLiveDeskRoute
  '/api/live/grok': typeof ApiLiveGrokRoute
  '/api/live/heart': typeof ApiLiveHeartRoute
  '/api/live/kalshi': typeof ApiLiveKalshiRoute
  '/api/live/kalshi-order': typeof ApiLiveKalshiOrderRoute
  '/api/live/leverage': typeof ApiLiveLeverageRoute
  '/api/live/perp-fire': typeof ApiLivePerpFireRoute
  '/api/live/pmus': typeof ApiLivePmusRoute
  '/api/live/price': typeof ApiLivePriceRoute
  '/api/live/pyth': typeof ApiLivePythRoute
  '/api/live/scan': typeof ApiLiveScanRoute
  '/api/live/skill': typeof ApiLiveSkillRoute
  '/api/live/swarm': typeof ApiLiveSwarmRouteWithChildren
  '/api/live/tape': typeof ApiLiveTapeRoute
  '/api/live/telegram': typeof ApiLiveTelegramRoute
  '/api/live/swarm/feed': typeof ApiLiveSwarmFeedRoute
  '/api/live/swarm/stream': typeof ApiLiveSwarmStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intel-grid'
    | '/paper'
    | '/research'
    | '/tap'
    | '/api/firecrawl/inbox'
    | '/api/firecrawl/intel'
    | '/api/firecrawl/pull'
    | '/api/firecrawl/radar'
    | '/api/firecrawl/webhook'
    | '/api/live/ask'
    | '/api/live/backtest'
    | '/api/live/brief'
    | '/api/live/brti'
    | '/api/live/desk'
    | '/api/live/grok'
    | '/api/live/heart'
    | '/api/live/kalshi'
    | '/api/live/kalshi-order'
    | '/api/live/leverage'
    | '/api/live/perp-fire'
    | '/api/live/pmus'
    | '/api/live/price'
    | '/api/live/pyth'
    | '/api/live/scan'
    | '/api/live/skill'
    | '/api/live/swarm'
    | '/api/live/tape'
    | '/api/live/telegram'
    | '/api/live/swarm/feed'
    | '/api/live/swarm/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intel-grid'
    | '/paper'
    | '/research'
    | '/tap'
    | '/api/firecrawl/inbox'
    | '/api/firecrawl/intel'
    | '/api/firecrawl/pull'
    | '/api/firecrawl/radar'
    | '/api/firecrawl/webhook'
    | '/api/live/ask'
    | '/api/live/backtest'
    | '/api/live/brief'
    | '/api/live/brti'
    | '/api/live/desk'
    | '/api/live/grok'
    | '/api/live/heart'
    | '/api/live/kalshi'
    | '/api/live/kalshi-order'
    | '/api/live/leverage'
    | '/api/live/perp-fire'
    | '/api/live/pmus'
    | '/api/live/price'
    | '/api/live/pyth'
    | '/api/live/scan'
    | '/api/live/skill'
    | '/api/live/swarm'
    | '/api/live/tape'
    | '/api/live/telegram'
    | '/api/live/swarm/feed'
    | '/api/live/swarm/stream'
  id:
    | '__root__'
    | '/'
    | '/intel-grid'
    | '/paper'
    | '/research'
    | '/tap'
    | '/api/firecrawl/inbox'
    | '/api/firecrawl/intel'
    | '/api/firecrawl/pull'
    | '/api/firecrawl/radar'
    | '/api/firecrawl/webhook'
    | '/api/live/ask'
    | '/api/live/backtest'
    | '/api/live/brief'
    | '/api/live/brti'
    | '/api/live/desk'
    | '/api/live/grok'
    | '/api/live/heart'
    | '/api/live/kalshi'
    | '/api/live/kalshi-order'
    | '/api/live/leverage'
    | '/api/live/perp-fire'
    | '/api/live/pmus'
    | '/api/live/price'
    | '/api/live/pyth'
    | '/api/live/scan'
    | '/api/live/skill'
    | '/api/live/swarm'
    | '/api/live/tape'
    | '/api/live/telegram'
    | '/api/live/swarm/feed'
    | '/api/live/swarm/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntelGridRoute: typeof IntelGridRoute
  PaperRoute: typeof PaperRoute
  ResearchRoute: typeof ResearchRoute
  TapRoute: typeof TapRoute
  ApiFirecrawlInboxRoute: typeof ApiFirecrawlInboxRoute
  ApiFirecrawlIntelRoute: typeof ApiFirecrawlIntelRoute
  ApiFirecrawlPullRoute: typeof ApiFirecrawlPullRoute
  ApiFirecrawlRadarRoute: typeof ApiFirecrawlRadarRoute
  ApiFirecrawlWebhookRoute: typeof ApiFirecrawlWebhookRoute
  ApiLiveAskRoute: typeof ApiLiveAskRoute
  ApiLiveBacktestRoute: typeof ApiLiveBacktestRoute
  ApiLiveBriefRoute: typeof ApiLiveBriefRoute
  ApiLiveBrtiRoute: typeof ApiLiveBrtiRoute
  ApiLiveDeskRoute: typeof ApiLiveDeskRoute
  ApiLiveGrokRoute: typeof ApiLiveGrokRoute
  ApiLiveHeartRoute: typeof ApiLiveHeartRoute
  ApiLiveKalshiRoute: typeof ApiLiveKalshiRoute
  ApiLiveKalshiOrderRoute: typeof ApiLiveKalshiOrderRoute
  ApiLiveLeverageRoute: typeof ApiLiveLeverageRoute
  ApiLivePerpFireRoute: typeof ApiLivePerpFireRoute
  ApiLivePmusRoute: typeof ApiLivePmusRoute
  ApiLivePriceRoute: typeof ApiLivePriceRoute
  ApiLivePythRoute: typeof ApiLivePythRoute
  ApiLiveScanRoute: typeof ApiLiveScanRoute
  ApiLiveSkillRoute: typeof ApiLiveSkillRoute
  ApiLiveSwarmRoute: typeof ApiLiveSwarmRouteWithChildren
  ApiLiveTapeRoute: typeof ApiLiveTapeRoute
  ApiLiveTelegramRoute: typeof ApiLiveTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-grid': {
      id: '/intel-grid'
      path: '/intel-grid'
      fullPath: '/intel-grid'
      preLoaderRoute: typeof IntelGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap': {
      id: '/tap'
      path: '/tap'
      fullPath: '/tap'
      preLoaderRoute: typeof TapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl/inbox': {
      id: '/api/firecrawl/inbox'
      path: '/api/firecrawl/inbox'
      fullPath: '/api/firecrawl/inbox'
      preLoaderRoute: typeof ApiFirecrawlInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl/intel': {
      id: '/api/firecrawl/intel'
      path: '/api/firecrawl/intel'
      fullPath: '/api/firecrawl/intel'
      preLoaderRoute: typeof ApiFirecrawlIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl/pull': {
      id: '/api/firecrawl/pull'
      path: '/api/firecrawl/pull'
      fullPath: '/api/firecrawl/pull'
      preLoaderRoute: typeof ApiFirecrawlPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl/radar': {
      id: '/api/firecrawl/radar'
      path: '/api/firecrawl/radar'
      fullPath: '/api/firecrawl/radar'
      preLoaderRoute: typeof ApiFirecrawlRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl/webhook': {
      id: '/api/firecrawl/webhook'
      path: '/api/firecrawl/webhook'
      fullPath: '/api/firecrawl/webhook'
      preLoaderRoute: typeof ApiFirecrawlWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/ask': {
      id: '/api/live/ask'
      path: '/api/live/ask'
      fullPath: '/api/live/ask'
      preLoaderRoute: typeof ApiLiveAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/backtest': {
      id: '/api/live/backtest'
      path: '/api/live/backtest'
      fullPath: '/api/live/backtest'
      preLoaderRoute: typeof ApiLiveBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/brief': {
      id: '/api/live/brief'
      path: '/api/live/brief'
      fullPath: '/api/live/brief'
      preLoaderRoute: typeof ApiLiveBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/brti': {
      id: '/api/live/brti'
      path: '/api/live/brti'
      fullPath: '/api/live/brti'
      preLoaderRoute: typeof ApiLiveBrtiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/desk': {
      id: '/api/live/desk'
      path: '/api/live/desk'
      fullPath: '/api/live/desk'
      preLoaderRoute: typeof ApiLiveDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/grok': {
      id: '/api/live/grok'
      path: '/api/live/grok'
      fullPath: '/api/live/grok'
      preLoaderRoute: typeof ApiLiveGrokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/heart': {
      id: '/api/live/heart'
      path: '/api/live/heart'
      fullPath: '/api/live/heart'
      preLoaderRoute: typeof ApiLiveHeartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/kalshi': {
      id: '/api/live/kalshi'
      path: '/api/live/kalshi'
      fullPath: '/api/live/kalshi'
      preLoaderRoute: typeof ApiLiveKalshiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/kalshi-order': {
      id: '/api/live/kalshi-order'
      path: '/api/live/kalshi-order'
      fullPath: '/api/live/kalshi-order'
      preLoaderRoute: typeof ApiLiveKalshiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/leverage': {
      id: '/api/live/leverage'
      path: '/api/live/leverage'
      fullPath: '/api/live/leverage'
      preLoaderRoute: typeof ApiLiveLeverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/perp-fire': {
      id: '/api/live/perp-fire'
      path: '/api/live/perp-fire'
      fullPath: '/api/live/perp-fire'
      preLoaderRoute: typeof ApiLivePerpFireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/pmus': {
      id: '/api/live/pmus'
      path: '/api/live/pmus'
      fullPath: '/api/live/pmus'
      preLoaderRoute: typeof ApiLivePmusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/price': {
      id: '/api/live/price'
      path: '/api/live/price'
      fullPath: '/api/live/price'
      preLoaderRoute: typeof ApiLivePriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/pyth': {
      id: '/api/live/pyth'
      path: '/api/live/pyth'
      fullPath: '/api/live/pyth'
      preLoaderRoute: typeof ApiLivePythRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/scan': {
      id: '/api/live/scan'
      path: '/api/live/scan'
      fullPath: '/api/live/scan'
      preLoaderRoute: typeof ApiLiveScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/skill': {
      id: '/api/live/skill'
      path: '/api/live/skill'
      fullPath: '/api/live/skill'
      preLoaderRoute: typeof ApiLiveSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/swarm': {
      id: '/api/live/swarm'
      path: '/api/live/swarm'
      fullPath: '/api/live/swarm'
      preLoaderRoute: typeof ApiLiveSwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/tape': {
      id: '/api/live/tape'
      path: '/api/live/tape'
      fullPath: '/api/live/tape'
      preLoaderRoute: typeof ApiLiveTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/telegram': {
      id: '/api/live/telegram'
      path: '/api/live/telegram'
      fullPath: '/api/live/telegram'
      preLoaderRoute: typeof ApiLiveTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/swarm/feed': {
      id: '/api/live/swarm/feed'
      path: '/feed'
      fullPath: '/api/live/swarm/feed'
      preLoaderRoute: typeof ApiLiveSwarmFeedRouteImport
      parentRoute: typeof ApiLiveSwarmRoute
    }
    '/api/live/swarm/stream': {
      id: '/api/live/swarm/stream'
      path: '/stream'
      fullPath: '/api/live/swarm/stream'
      preLoaderRoute: typeof ApiLiveSwarmStreamRouteImport
      parentRoute: typeof ApiLiveSwarmRoute
    }
  }
}

interface ApiLiveSwarmRouteChildren {
  ApiLiveSwarmFeedRoute: typeof ApiLiveSwarmFeedRoute
  ApiLiveSwarmStreamRoute: typeof ApiLiveSwarmStreamRoute
}

const ApiLiveSwarmRouteChildren: ApiLiveSwarmRouteChildren = {
  ApiLiveSwarmFeedRoute: ApiLiveSwarmFeedRoute,
  ApiLiveSwarmStreamRoute: ApiLiveSwarmStreamRoute,
}

const ApiLiveSwarmRouteWithChildren = ApiLiveSwarmRoute._addFileChildren(
  ApiLiveSwarmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntelGridRoute: IntelGridRoute,
  PaperRoute: PaperRoute,
  ResearchRoute: ResearchRoute,
  TapRoute: TapRoute,
  ApiFirecrawlInboxRoute: ApiFirecrawlInboxRoute,
  ApiFirecrawlIntelRoute: ApiFirecrawlIntelRoute,
  ApiFirecrawlPullRoute: ApiFirecrawlPullRoute,
  ApiFirecrawlRadarRoute: ApiFirecrawlRadarRoute,
  ApiFirecrawlWebhookRoute: ApiFirecrawlWebhookRoute,
  ApiLiveAskRoute: ApiLiveAskRoute,
  ApiLiveBacktestRoute: ApiLiveBacktestRoute,
  ApiLiveBriefRoute: ApiLiveBriefRoute,
  ApiLiveBrtiRoute: ApiLiveBrtiRoute,
  ApiLiveDeskRoute: ApiLiveDeskRoute,
  ApiLiveGrokRoute: ApiLiveGrokRoute,
  ApiLiveHeartRoute: ApiLiveHeartRoute,
  ApiLiveKalshiRoute: ApiLiveKalshiRoute,
  ApiLiveKalshiOrderRoute: ApiLiveKalshiOrderRoute,
  ApiLiveLeverageRoute: ApiLiveLeverageRoute,
  ApiLivePerpFireRoute: ApiLivePerpFireRoute,
  ApiLivePmusRoute: ApiLivePmusRoute,
  ApiLivePriceRoute: ApiLivePriceRoute,
  ApiLivePythRoute: ApiLivePythRoute,
  ApiLiveScanRoute: ApiLiveScanRoute,
  ApiLiveSkillRoute: ApiLiveSkillRoute,
  ApiLiveSwarmRoute: ApiLiveSwarmRouteWithChildren,
  ApiLiveTapeRoute: ApiLiveTapeRoute,
  ApiLiveTelegramRoute: ApiLiveTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
